import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface RoomForPDF {
  name: string;
  theme: string;
  created_at: string;
  questions: Array<{ id: string; text: string }>;
  answers: Array<{ question_id: string; text: string; author_nickname: string }>;
}

interface AnswerForPDF {
  question_id: string;
  text: string;
  author_nickname: string;
}

const getColors = (theme: string) => {
  if (theme === 'horse') {
    return {
      bg: '#1f1212',
      card: '#2a1a1a',
      primary: '#e62e2e',
      secondary: '#f2a122',
      accent: '#ffc929',
      text: '#fff9e6',
      muted: '#d4c4a8',
    };
  }
  return {
    bg: '#0d2b1f',
    card: '#143327',
    primary: '#e63333',
    secondary: '#1c8f4f',
    accent: '#ffc107',
    text: '#fff9e6',
    muted: '#d4c4a8',
  };
};

export const generateResultsPDF = async (
  room: RoomForPDF,
  answersByParticipant: Record<string, AnswerForPDF[]>
): Promise<void> => {
  const c = getColors(room.theme);
  const participants = Object.keys(answersByParticipant);
  const themeText = room.theme === 'horse' ? '🐴 2026 붉은 말' : '🎄 크리스마스';
  
  // Build questions HTML
  let qHtml = '';
  room.questions.forEach((q, i) => {
    const qAnswers = room.answers.filter(a => a.question_id === q.id);
    let aHtml = '';
    if (qAnswers.length === 0) {
      aHtml = `<div style="color:${c.muted};font-size:13px;">답변이 없습니다</div>`;
    } else {
      qAnswers.forEach(a => {
        aHtml += `<div style="background:${c.bg};padding:12px;margin-bottom:10px;border-left:4px solid ${c.primary};">
          <div style="font-size:14px;color:${c.text};margin-bottom:8px;line-height:1.6;">${a.text}</div>
          <div style="font-size:12px;color:${c.accent};font-weight:bold;">— ${a.author_nickname}</div>
        </div>`;
      });
    }
    qHtml += `<div style="background:${c.card};border:3px solid ${c.secondary};padding:15px;margin-bottom:20px;">
      <div style="font-size:16px;font-weight:bold;color:${c.accent};margin-bottom:15px;">Q${i+1}. ${q.text}</div>
      ${aHtml}
    </div>`;
  });

  // Build participants HTML
  let pHtml = '';
  Object.entries(answersByParticipant).forEach(([name, answers]) => {
    let paHtml = '';
    answers.forEach(a => {
      const q = room.questions.find(x => x.id === a.question_id);
      const idx = room.questions.findIndex(x => x.id === a.question_id) + 1;
      paHtml += `<div style="background:${c.card};padding:12px;margin-bottom:8px;margin-left:15px;">
        <div style="font-size:11px;color:${c.muted};font-style:italic;margin-bottom:5px;">Q${idx}. ${q?.text || ''}</div>
        <div style="font-size:14px;color:${c.text};line-height:1.6;">${a.text}</div>
      </div>`;
    });
    pHtml += `<div style="margin-bottom:25px;">
      <div style="background:${c.primary};color:${c.text};padding:10px 15px;font-size:14px;font-weight:bold;margin-bottom:10px;border:3px solid ${c.accent};">
        ${name} (${answers.length}개 답변)
      </div>
      ${paHtml}
    </div>`;
  });

  const html = `
    <div style="text-align:center;padding:40px;margin-bottom:30px;border:4px solid ${c.accent};background:${c.card};">
      <div style="font-size:32px;font-weight:bold;color:${c.accent};margin-bottom:10px;">${room.name}</div>
      <div style="font-size:16px;color:${c.text};margin-bottom:20px;">UNBOX US - 최종 결과</div>
      <div style="display:inline-block;background:${c.primary};color:${c.text};padding:8px 20px;font-size:14px;margin-bottom:15px;">${themeText}</div>
      <div style="color:${c.muted};font-size:14px;">
        참여자 ${participants.length}명 · 질문 ${room.questions.length}개<br/>
        생성일: ${new Date(room.created_at).toLocaleDateString('ko-KR')}
      </div>
    </div>
    <div style="margin-bottom:30px;">
      <div style="font-size:20px;font-weight:bold;color:${c.accent};margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid ${c.accent};">📋 질문별 답변 모음</div>
      ${qHtml}
    </div>
    <div style="margin-bottom:30px;">
      <div style="font-size:20px;font-weight:bold;color:${c.accent};margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid ${c.accent};">👥 참여자별 답변 요약</div>
      ${pHtml}
    </div>
    <div style="text-align:center;padding:20px;color:${c.muted};font-size:12px;margin-top:40px;border-top:2px solid ${c.accent};">
      Generated by Unbox Us 🎁
    </div>
  `;

  const container = document.createElement('div');
  container.style.cssText = `position:fixed;left:-9999px;top:0;width:800px;font-family:'Galmuri9','Malgun Gothic',sans-serif;background:${c.bg};color:${c.text};padding:40px;box-sizing:border-box;`;
  container.innerHTML = html;
  document.body.appendChild(container);

  try {
    await document.fonts.ready;
    await new Promise(r => setTimeout(r, 100));
    
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: c.bg,
      logging: false,
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = pdf.internal.pageSize.getHeight();
    const ratio = pdfW / (canvas.width / 2);
    const scaledH = (canvas.height / 2) * ratio;
    
    let left = scaledH;
    let pos = 0;
    pdf.addImage(imgData, 'PNG', 0, pos, pdfW, scaledH);
    left -= pdfH;
    
    while (left > 0) {
      pos = left - scaledH;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, pos, pdfW, scaledH);
      left -= pdfH;
    }
    
    pdf.save(`${room.name.replace(/[^a-zA-Z0-9가-힣]/g, '_')}_결과.pdf`);
  } finally {
    document.body.removeChild(container);
  }
};
